### ISSUE TITLE
Request: Redirect back to Nova

### ISSUE THREAD

**Issue by daugaard47** [RhysLees/nova-impersonating-banner#1]
On `stopImpersonating` Is there a way to customize this to redirect back to Nova in this snippet?

**Livewire/NovaImpersonatingBanner.php**
```
    public function stopImpersonating()
    {
        app(ImpersonatesUsers::class)->stopImpersonating(request(), Auth::guard('web'), User::class);

        return redirect(request()->header('Referer'));
    }
```

Something like this: 
```
return redirect()->to('/nova');
```

I don't see an option to publish this file..

**Comment by RhysLees** [comment]
Just pushed an update to allow you to change this.

You just need to publish the new config file:

```bash
php artisan vendor:publish --provider="RhysLees\NovaImpersonatingBanner\NovaImpersonatingBannerServiceProvider" --tag="config"
```

https://github.com/RhysLees/nova-impersonating-banner/releases/tag/v1.1.0

**Comment by daugaard47** [comment]
Thanks so much for adding this so quickly. Much appreciated!

**Comment by RhysLees** [comment]
> Thanks so much for adding this so quickly. Much appreciated!

Not a problem!

Also planning to add an inertia version soon for the other side of jetstream
