### ISSUE TITLE
Nova 4

### ISSUE THREAD

**Issue by scramatte** [RhysLees/nova-impersonating-banner#3]
Hello,

It look that documentation is outdaded for Nova 4.
On my install I don't have any blade file. What I've missed?

Regards

**Comment by RhysLees** [comment]
did you run the following?
 ```bash
php artisan vendor:publish --provider="RhysLees\NovaImpersonatingBanner\NovaImpersonatingBannerServiceProvider"
```

You may also need to follow this answer which ill add to the docs if that's the case:
https://github.com/laravel/nova-issues/discussions/3989#discussioncomment-2564037
